In [2]:
import numpy as np

## Get a two dimensional array full with zeros and use slicing to change

In [17]:
A = np.zeros((6,6), dtype=int)
print(A)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [18]:
A[0::2, 0::2]= A[0::2, 0::2] + 10
A[1::2, 0::2]= A[1::2, 0::2] + 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


## Combine two arrays

In [19]:
A = np.arange(12).reshape(-1, 4)

B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 3 7 2]
 [0 5 2 6]]


In [23]:
print(np.append(A,B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


## Intersection between two arrays

In [25]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])    
print(A)
print(B)

[[0 1 2 3]
 [4 5 6 7]]
[[ 9 10 11  3]
 [ 2  8  0  9]]


In [26]:
print(np.intersect1d(A,B))

[0 2 3]


## Unique values of an array

In [27]:
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(np.unique(A))

[1 2 4 5 7 9]


## List of indexes array of maximum values

In [30]:
A = np.array([[0.4, 0.3, 0.3],
            [0.1, 0.1, 0.8],
            [0.2, 0.5, 0.3]])
print(np.argmax(A, axis=0))

[0 2 1]


## Sort array by column and row

In [35]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
A_0 = np.sort(A, axis=0)
A_1 = np.sort(A, axis=1)
print(A_1)
print(A_0)

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


## Aplicar condiciones con Where

In [41]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
              
print(A[np.where(A>8)])

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

print(np.where(A<=10, A, 10))

[ 9.99  9.99 14.99]
[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


## Flattened two dimensional array into one dimensional array

In [42]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
print(np.ravel(A, order='C'))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


## Lower triangular matrix

In [43]:
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


## Expand dimensions

In [49]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
              
print(A.shape)
B = np.expand_dims(A, axis=0)
print(B)
print(B.shape)

(2, 3)
[[[4 2 1]
  [6 4 2]]]
(1, 2, 3)


## Reduce dimensions

In [50]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])

print(np.squeeze(A, axis=0))

A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
              
print(np.squeeze(A, axis=1))

[[1 2 3]
 [6 3 2]]


## Change the order of the elements of the array

In [12]:
A = np.arange(12, dtype='int').reshape(-1, 4)

print(A[::-1,::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


## Split array into multiples array

In [74]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A11, B11, C11 = np.split(A, [2,6], axis=1)

A1 = np.split(A, [2,6,8], axis=1)[0]
A2 = np.split(A, [2,6,8], axis=1)[1]
A3 = np.split(A, [2,6,8], axis=1)[2]
print(A1)
print(A11)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


## Zeros count

In [75]:
np.random.seed(42)

A = np.random.randint(low=0, high=2, size=(10, 6))

print(np.count_nonzero(A))

31


## Numpy configurations

In [ ]:
np.set_printoptions(precision=8)

np.set_printoptions(suppress=True)

np.set_printoptions(edgeitems=10)

## Delete columns of an array

In [76]:
np.random.seed(42)

A = np.random.randn(8, 4)

print(np.delete(A, 2, axis=1))

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


## Calculate the norm of a matrix

In [77]:
v = np.array([3, 4, -2])

print(np.linalg.norm(v))

5.385164807134504


## Calculate mean of an array

In [80]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
print(np.mean((A, B), axis=0))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


## Calculate the determinant of a matrix 

In [83]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
              
print(np.linalg.det(A))

51.999999999999986


## Calculate the eigenvalues 

In [86]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
print(np.linalg.eig(A).eigenvalues)
print(np.linalg.eig(A).eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


## Calculate the inverse matrix

In [87]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


## Sum of elements of the main diagonal

In [88]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
print(np.trace(A))

-5


## Dot product

In [97]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

B = B.reshape(2,4)

print(np.dot(A, B))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


%md
## Operations between two arrays with different shapes

In [109]:
W = np.array([4,5,1])
Q = np.array([2,4,-5,1])

print(np.polyadd(W,Q))
print(np.polysub(W,Q))
print(np.polymul(W,Q))
print(np.polyadd(W,2*Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


## Create an array with different dates

In [111]:
# Define the start and end dates
start_date = np.datetime64('2023-01-01')
end_date = np.datetime64('2023-01-10')

# Generate an array of dates in a specified range
date_range = np.arange(start_date, end_date, np.timedelta64(1, 'D'))
print(date_range)   

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09']


In [112]:

print(np.arange('2021-01', '2022-01', dtype='datetime64[M]'))

['2021-01' '2021-02' '2021-03' '2021-04' '2021-05' '2021-06' '2021-07'
 '2021-08' '2021-09' '2021-10' '2021-11' '2021-12']


## Union of two arrays by each value

In [3]:
A = np.array(['001', '002', '003'], dtype=str)
B = np.array(['XC', 'YC', 'ZC'], dtype=str)

print(np.char.add(A, B))

['001XC' '002YC' '003ZC']


## Strip, replace and start with functions

In [7]:
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
print(np.char.strip(np.char.replace(A, '#', ' ')))
#stocks_startswith_P = result[np.char.startswith(result, 'P')[:,0]]

[['summer time mood']
 ['sport time']]


## Example 01 - Sum and round the array

In [44]:
np.set_printoptions(linewidth=150)
stocks_startswith_P = np.array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')
print(np.round(stocks_startswith_P[:,4].astype(np.float32).sum(), 2))

49.49


## Example 02 - Create a array from string

In [50]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

initial_split = wig_games_raw.split('\n')
second_split = [row.split('\t') for row in initial_split]
wig_games = np.array(second_split)
wig_games = np.char.replace(wig_games, ' ', '')
print(wig_games)

[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High' 'Volume' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '+8.00' '(+2.09%)' '383.00' '383.50' '383.00' '394.00' '12784' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '+5.30' '(+1.59%)' '334.20' '338.30' '337.00' '344.20' '233059' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '-0.012' '(-1.59%)' '0.754' '0.772' '0.730' '0.772' '1311078' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '+18.00' '(+4.87%)' '369.50' '374.00' '373.00' '388.00' '33206' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '+22.50' '(+6.88%)' '327.00' '332.00' '330.00' '353.50' '39793' '13697060' '28.855%']]


In [53]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

initial_split = playway_raw.split('\n')
second_split = [row.split(',') for row in initial_split]
playway = np.array(second_split)
print(playway)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

## Example 03 - Eliminate columns of an array

In [38]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games = np.array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')

i, j = np.where(wig_games == 'Change') 
first = np.delete(wig_games, j[0], axis=1)
i, j = np.where(first == 'Change%') 
second = np.delete(first, j[0], axis=1)
i, j = np.where(second == 'Ref.') 
third = np.delete(second, j[0], axis=1)
i, j = np.where(third == 'Volume') 
four = np.delete(third, j[0], axis=1)
print(four)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


## Example 04 - Save a file and then read it

In [50]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games = np.array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')

np.savetxt('wig_games.csv', wig_games,fmt='%s', delimiter=',')
wig_games_new = np.loadtxt('wig_games.csv', delimiter=',',dtype=str)
print(wig_games_new)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


## Example 05 - Remove column Date and remove headers

In [57]:
playway = np.array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
       ['2020-03-23', '274', '289', '258', '285', '37098'],
       ['2020-03-24', '305', '309', '296.5', '309', '31939'],
       ['2020-03-25', '313', '330', '295', '304', '46724'],
       ['2020-03-26', '300', '309', '295.5', '300', '27213'],
       ['2020-03-27', '302', '306.5', '290', '296', '13466'],
       ['2020-03-30', '299', '300', '287', '300', '10316'],
       ['2020-03-31', '302.5', '309', '302', '306.5', '15698']],
      dtype='<U10')


i, j = np.where(playway == 'Date') 
playway_values = np.delete(playway, j[0], axis=1)

playway_values = playway_values[1:,:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

## Example 06 - Calculate the average value of each column and round two 2

In [60]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])

print(playway_values.mean(axis=0).round(2))

[  283.14   295.25   268.69   282.3  48688.05]


## Example 07 - Get max - min difference column

In [89]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
max_values = playway_values.max(axis=1)
min_values = playway_values.min(axis=1)
max_min_diff = max_values - min_values
playway_values = np.append(playway_values, max_min_diff.reshape(22,1), axis=1)

print(playway_values)

[[   305.     324.5    283.5    310.   64081.   63797.5]
 [   325.5    340.5    320.     340.5  55496.   55176. ]
 [   324.     340.5    315.     330.   36152.   35837. ]
 [   344.     344.     310.     315.   35992.   35682. ]
 [   306.5    307.     291.     305.   32539.   32248. ]
 [   274.     291.     250.     258.   79402.   79152. ]
 [   278.     284.5    256.     264.   35700.   35444. ]
 [   270.     270.     238.5    245.   60445.   60206.5]
 [   218.     228.     196.     197.   94031.   93835. ]
 [   210.     229.     198.8    211.  100412.  100213.2]
 [   205.     248.     197.8    240.5  50659.   50461.2]
 [   245.     269.     232.5    264.   99480.   99247.5]
 [   264.     280.     251.     270.   70136.   69885. ]
 [   267.     280.     267.     279.5  30732.   30465. ]
 [   297.5    307.     280.     280.5  43426.   43146. ]
 [   274.     289.     258.     285.   37098.   36840. ]
 [   305.     309.     296.5    309.   31939.   31642.5]
 [   313.     330.     295.    

## Example 08 - Order descending and get first 10 rows

In [107]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
print(playway_values[playway_values[:, -2].argsort()[::-1]][:10,:])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


## Example 09 - Create a column based on conditions

In [115]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

result = np.where(playway_values[:,-3] > playway_values[:,0], 1, 0)
print(np.append(playway_values, result.reshape(len(result),1), axis=1) )

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

## Example 10 - Resolve an equation

In [11]:
#5x - 3y = 21
#x -2y = 7

a = np.array([[5,-3], [1,-2]])
b = np.array([21,7])
x,y = np.linalg.solve(a, b)

print('x =', x)
print('y =', y)

x = 3.0
y = -2.0
